### PR TITLE
Upgrade Illuminate from v6 to v7

### PR DESCRIPTION
**Pull request by jooola**
Dependencies upgrade
- orchestra/testbench to ^5

### CODE REVIEW

**Comment by jooola** [comment]
Have to fixes these before merging, I'll open a ticket at https://github.com/nunomaduro/larastan
```
 ------ ------------------------------------------------------------- 
  Line   src/Laravel/Providers/DirectusProvider.php                   
 ------ ------------------------------------------------------------- 
  52     Dynamic call to static method                                
         Illuminate\Foundation\Application::configurationIsCached().  
  95     Dynamic call to static method                                
         Illuminate\Foundation\Application::routesAreCached().        
 ------ ------------------------------------------------------------- 
```

**Comment by WoLfulus** [comment]
🤦

**Comment by jooola** [comment]
That was definitely too fast.

**Comment by WoLfulus** [comment]
I had to do it anyways because freshly installed laravel projects are already defaulting to v7, which wasn't allowing me to install directus package at all.

**Pull request merged**
